config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', :registrations => 'registrations' }

  match '/profile/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :users, only: [:update, :show]
  # The default page when user enters home page URL
  root to: 'welcome#about'

  get 'welcome/index'

  get 'welcome/about'

  resources :todos do
    # route for 'done' controller method in todos for marking action as complete
    member do
      get 'done'
    end
  end


end

app/models/todo.rb
class Todo < ActiveRecord::Base
  # checks that todo is created with a description and a due days integer
  validates :description, presence: true
  validates :duedays, presence: true
  

  # a Todo item must belong to one user
  belongs_to :user

  # sort Todos by due date (i.e. closest due date at top!)
  default_scope { order('due ASC') }

  def expired?
    Time.now >= self.due
  end


  # # Called whenever a new Active Record object is instantiated (via 'new' or retrieval)
  # after_initialize :init
  # # Because initialize is called when 'new' Todo is called
  # # and when todo record retrieved, need to avoid overwriting due date
  # # so use conditional assignment (assigns variable only if it's new_record or, nil)
  # # i.e. the due date will only be set upon new creation of todo
  # def init
  #   self.duedays = 0
  #   if self.new_record? && self.due.nil?
  #     self.due ||= (Time.now + self.duedays.days)
  #   end
  # end




end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todos = current_user.todos
    @todo = Todo.new
    @todo.due = Time.now
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new 
  end

  def create
    if current_user.todos.count >= 5
      flash[:alert] = "You have too many items. Please remove one then try again."
      redirect_to todos_path
    else
      @todo = current_user.todos.build(todo_params)
      @todo.due = Time.now + (@todo.duedays.days)

      if @todo.save
        flash[:notice] = "Your Todo item saved."
        redirect_to todos_path
      else
        flash[:error] = "You entered an empty ToDo item. Please try again."
        redirect_to todos_path
      end
    end
  end 


  def update
    @todo = current_user.todos.find(params[:id])

    if @todo.update_attributes(todo_params)
      flash[:notice] = "Todo was updated."
      redirect_to todos_path
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :show
    end
  end



  # Will delete todo item in the user's bitlist
  def destroy
    @todo = current_user.todos.find(params[:id])

    if @todo.destroy
      flash[:notice] = "Your todo was item deleted!"
      redirect_to todos_path
    else
      flash[:error] = "Could not delete item. Please try again."
      redirect_to todos_path
    end
  end

  # delete item and give incrememet completed items by 1
  def done
    @todo =current_user.todos.find(params[:id])

    if @todo.destroy
      # update completed/missed items number for user and save changes to dB
      if @todo.expired?
        current_user.missed += 1
      else
        current_user.completed += 1
      end
      current_user.save

      flash[:notice] = "Yay! Your item was completed!"
      redirect_to todos_path
    else
      flash[:error] = "Could not clear item. Please try again."
      redirect_to todos_path
    end
  end


  private

  def todo_params
    params.require(:todo).permit(:description, :duedays)
  end


end

app/views/todos/index.html.erb
<blockquote>
  <p class="text-info">Welcome to Bit List.</p>
</blockquote>



<%= form_for Todo.new, :url => { :action => "create" } do |f| %>
  <div class="form-group">
    <div class="input-group">
      <span class="input-group-addon">
        <%= f.select(:duedays, options_for_select([['Due in 1 Day', 1], ['Due in 3 Days', 3],['Due in 7 Days', 7]])) %>
      </span>
      <%= f.text_field :description, :autocomplete => :off, :maxlength => "70", class: 'form-control', placeholder: "Enter description of todo here..." %>
      <span class="input-group-btn">
        <%= f.submit "Add", class: "btn btn-default"%>
      </span>
    </div>
<% end %>


<div id="counter" class="counter">
  <p class="text-muted">70 characters left</p>
</div>

<hr>
<!-- script for char count down -->
<script>
  $(document).ready(function() {
    $("#todo_description").keyup(function() {
      var counter = $("#counter");
      var charsRemaining = 70 - $(this).val().length;
      counter.text(charsRemaining + " characters left");
      counter.css('color', (charsRemaining < 35) ? 'red' : 'grey');
    });
  });
</script>
<!-- END of script for char count down -->


<div class="panel panel-info">
  <div class="panel-heading">
    <p class="panel-title">My Todos</p>
  </div>
  <div class="panel-body">

  <!-- will want row of colors to depend on ranking of item, i.e. one due soon to be danger color class!-->
  <!-- see how tables look here http://bootswatch.com/readable/ -->
  <table class="table table-striped table-hover">
    
    <!-- table heading -->
    <thead>
      <tr>
        <th>Item</th>
        <th>Time Left</th>
        <th>Action</th>
      </tr>
    </thead>
    <!-- end of table heading -->

    <!-- start of the table body i.e. rows -->
    <tbody>
      <!-- start of the table rows -->
      <% @todos.each do |todo| %>
        <tr>   
          
          <!-- Item details -->
          <td>
            <%= todo.description %>
          </td>

          <!-- Item deadline -->
          <td>
            <% if todo.expired? %>
              <p class="text-danger">expired <%= distance_of_time_in_words(todo.due, DateTime.now)%> ago</p>
            <% else %>
              <%= distance_of_time_in_words(todo.due, DateTime.now)%> left
            <% end %>
          </td>

          <!-- Item actions -->
          <td>  
            <div class="btn-group">
              <!-- Done button -->
              <%= link_to done_todo_path(todo), data: { confirm: "Are you sure item is complete?" }, :class => "btn btn-default" do %>
                <span class="glyphicon glyphicon-ok-circle"></span>
                Done
              <% end %>
              
              <!-- Dropdown button for Amend/Delete -->
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to todo do %>
                    <i class="fa fa-pencil fa-fw"></i>
                    Amend
                  <% end %>
                </li> 
                <li class="divider"></li>
                
                <li>
                  <%= link_to todo, data: { confirm: "Are you sure you wish to delete this item?" }, method: :delete do %>
                  <i class="fa fa-trash-o fa-fw"></i>
                  Delete
                  <% end %> 
                </li>


              </ul>
            </div>
          </td>           
        </tr>
      <% end %>

    </tbody>
    <!-- END of table body rows  -->

  </table> 
  <!-- END of table -->
  </div>
</div>  

app/views/todos/new.html.erb
<%= form_for @todo do |form| %>  

  <div class="form-group">
    <%= form.text_field :description, placeholder: 'Description', class: 'form-control' %>
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>

<% end %> 

app/views/todos/show.html.erb
<br>
<blockquote>
  <p class="text-info">Amend Your Todo Item Below</p>
</blockquote>
<br>
<!-- Enter todo item - form -->
<%= form_for @todo, :url => { :action => "update" } do |f| %>
  
  <div class="form-group">
    <div class="input-group">
      <%= f.text_field :description, :autocomplete => :off, :maxlength => "70", class: 'form-control', placeholder: "Enter amended todo item here..." %>
      <span class="input-group-btn">
        <%= f.submit "Update", class: "btn btn-default" %>
      </span>
    </div> 
  </div>    
<% end %>

<div id="counter" class="counter-amend-page">
  <p class="text-muted">70 characters left</p>
</div>

<!-- Delete Post Button -->
<%= link_to "Delete Todo", @todo, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this todo item?'} %>
<!-- End of Delete Post Button -->



<!-- script for char count down -->
<script>
  $(document).ready(function() {
    $("#todo_description").keyup(function() {
      var counter = $("#counter");
      var charsRemaining = 70 - $(this).val().length;
      counter.text(charsRemaining + " characters left");
      counter.css('color', (charsRemaining < 35) ? 'red' : 'grey');
    });
  });
</script>
<!-- END of script for char count down -->