config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', :registrations => 'registrations' }

  match '/profile/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :users, only: [:update, :show]
  # The default page when user enters home page URL
  root to: 'welcome#about'

  get 'welcome/index'

  get 'welcome/about'

  resources :todos do
    # route for 'done' controller method in todos for marking action as complete
    member do
      get 'done'
    end
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bitlist</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body> 
  <div class="container">
    
    <div class="navboarder">
    <!-- menu -->
    <ul class="nav nav-pills">

      <li>
        <%= link_to welcome_about_path do %>
          <i class="fa fa-desktop"></i>
          About
        <% end %>
      </li>

      <li>
        <%= link_to "http://michaeltefula.com/contact/", :target => "_blank" do %>
          <i class="fa fa-envelope-o"></i>
          Contact Author
        <% end %>
      </li>

      <!--  sign-out and sign-in/up buttons-->
      <div class="pull-right user-info">
        <% if current_user %>          
          <ul class="nav nav-pills">
            <li>
              <%= link_to todos_path do %>
                My Todos
                <span class="badge"><%= current_user.todos.count %></a>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
                My Profile
              <% end %>
            </li>
            <li>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
            </li>
          </ul>       
        <% else %>
        <ul class="nav nav-pills">
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        </ul>
        <% end %>
      </div>
      <!-- END of sign-in/out and sign-up buttons-->
    </ul>
    <!-- end of menu -->
   </div>

    <!-- Flash Notices Area -->
    <% if flash[:notice] %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>

    <% elsif flash[:error] %>
      <div class="alert alert-dismissable alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
      
    <% elsif flash[:alert] %>
      <div class="alert alert-dismissable alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
    </div>
    <% end %>
    <!-- End of Flash Notices Area -->
  </div>

  <div class="container">
    <!-- main content -->
    <%= yield %>
    <!-- main content -->
  </div>


</body>
</html>